/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.MissaoDAO;
import DAO.RotaDAO;
import java.util.ArrayList;
import java.util.List;
import model.Agente;
import model.Faturamento;
import model.Missao;
import model.Rota;

/**
 *
 * @author rafa_
 */
public class TelaFaturamento extends javax.swing.JInternalFrame {

    /**
     * Creates new form Faturamento
     */
    public TelaFaturamento() {
        initComponents();
    }

    
    public void Faturamento(){
        MissaoDAO mDAO = new MissaoDAO();
        RotaDAO rDAO = new RotaDAO();
        List<Missao> missao = new ArrayList<Missao>();
        List<Rota> rota = new ArrayList<Rota>();
        List<Faturamento> faturamento = new ArrayList<Faturamento>();
        Faturamento f = new Faturamento();
        rota = rDAO.read();
        missao = mDAO.read();
        
        for(int i=0;i<missao.size();i++){
            for(int j=0;j<rota.size();j++){
                if(missao.get(i).getRota() == rota.get(j).getId()){
                    f.setAgente(Agente.converterAgente(missao.get(i).getAgente()));
                    f.setKmPercorrido(missao.get(i).getTotalKM());
                    faturamento.add(f);
                    
                }
            }
        }
        
        System.out.println(faturamento.toString());
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
